version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Optional: Add a local blockchain for development
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0 --accounts 10 --balance 10000
    ports:
      - "8545:8545"
    restart: unless-stopped
    profiles:
      - development